@baseUrl = http://localhost:8080
@userToken = Bearer 
@adminToken = Bearer 
@user2Token = Bearer 

### AUTH

### Login (user / admin)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@local.dev",
  "password": "12345"
}

### USERS (SELF)

### Get all users
GET {{baseUrl}}/users
Authorization: {{userToken}}

### Get my info
GET {{baseUrl}}/users/me
Authorization: {{adminToken}}

### Get user by id
GET {{baseUrl}}/users/6
Authorization: {{adminToken}}

### Create user (public)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "userPsd@local.dev",
  "password": "12345",
  "profile": {
    "name": "fd"
  }
}

### delete user
DELETE {{baseUrl}}/users/1
Authorization: {{adminToken}}

### Self update
PUT {{baseUrl}}/users/6
Authorization: {{userToken}}
Content-Type: application/json

{  
  "password": "probandotodo",
  "profile": {
    "name": "    ",
    "avatar": "https://exampleSelf.com/avatar.png"
  }
}

### Self delete (soft delete)
DELETE {{baseUrl}}/users/me
Authorization: {{userToken}}

### =========================
### ADMIN – USERS
### =========================

### Admin update user
PUT {{baseUrl}}/admin/users/8
Authorization: {{adminToken}}
Content-Type: application/json

{
  "email": "userl@local.dev",
  "password": "probandotodo",
  "profile": {
    "name": "CarlosEd",
    "avatar": "https://example.com/avatar.png"
  },
  "systemRoleId": 2
}

### Admin delete user (soft delete)
DELETE {{baseUrl}}/admin/users/10
Authorization: {{adminToken}}

### Restore user (admin)
PUT {{baseUrl}}/admin/users/2/restore
Authorization: {{adminToken}}


### BOARDS
### Create board
POST {{baseUrl}}/boards
Authorization: {{userToken}}
Content-Type: application/json

{
  "name": "board de prueba2"
}

### Get all boards
GET {{baseUrl}}/boards
Authorization: {{userToken}}

### Get board by id
GET {{baseUrl}}/boards/1
Authorization: {{userToken}}

### Update board
PUT {{baseUrl}}/boards/1
Authorization: {{userToken}}
Content-Type: application/json

{
  "name": "board de pruebadWS2"
}

### Soft delete board by id
DELETE {{baseUrl}}/boards/8
Authorization: {{userToken}}

### Restore board by id
PUT {{baseUrl}}/boards/8/restore
Authorization: {{userToken}}

### Add user as member to board
POST {{baseUrl}}/boards/1/invite
Authorization: {{userToken}}
Content-Type: application/json

{
  "email": "userP@local.dev"
}

### Remove member from board
DELETE {{baseUrl}}/boards/1/remove/3
Authorization: {{userToken}}

### Update board member role
PUT {{baseUrl}}/boards/9/members/4/role
Authorization: {{userToken}}
Content-Type: application/json

{
  "role": "admin"
}

### Get board members with board roles by board id
GET {{baseUrl}}/boards/1/members
Authorization: {{userToken}}

### Transfer ownership
PUT {{baseUrl}}/boards/9/transfer-ownership/4
Authorization: {{userToken}}


### LISTS
### Create list
POST {{baseUrl}}/boards/1/lists
Authorization: {{userToken}}
Content-Type: application/json

{
  "title": "my listlast"
}

### Get lists by board Id
GET {{baseUrl}}/boards/1/lists
Authorization: {{userToken}}

### Get list by Id
GET {{baseUrl}}/boards/1/lists/9
Authorization: {{userToken}}

### Update list
PUT {{baseUrl}}/boards/1/lists/4
Authorization: {{userToken}}
Content-Type: application/json

{
  "title": "list de pruebad"
}

### Update list position
PUT {{baseUrl}}/boards/1/lists/4/position
Authorization: {{userToken}}
Content-Type: application/json

{  
  "prevListId": 2,
  "nextListId": 3
}

### Remove list by Id
DELETE {{baseUrl}}/boards/1/lists/7
Authorization: {{userToken}}

### CARDS
### Create card
POST {{baseUrl}}/boards/1/lists/10/cards
Authorization: {{userToken}}
Content-Type: application/json

{
  "title": "my cards title",
  "description": "my descr"
}

### Update card
PUT {{baseUrl}}/boards/1/lists/1/cards/11
Authorization: {{userToken}}
Content-Type: application/json

{
  "title": "my cards title UPda",
  "description": "my descrUP"
}

### Get cards by list Id
GET {{baseUrl}}/boards/1/lists/10/cards
Authorization: {{userToken}}

### Get card by Id
GET {{baseUrl}}/boards/1/lists/1/cards/1
Authorization: {{userToken}}

### Remove card by Id
DELETE {{baseUrl}}/boards/1/lists/10/cards/11
Authorization: {{userToken}}

### Update card position
PUT {{baseUrl}}/boards/1/cards/11/position
Authorization: {{userToken}}
Content-Type: application/json

{
  "targetListId": 10,
  "prevCardId": 29,
  "nextCardId": 30
}

### CARD MEMBERS
### Add user to card
POST {{baseUrl}}/boards/1/cards/11/members
Authorization: {{userToken}}
Content-Type: application/json

{
  "userId": 3
}

### Remove user from card
DELETE {{baseUrl}}/boards/1/cards/11/members/3
Authorization: {{userToken}}

### Get members of a card by id
GET  {{baseUrl}}/boards/1/cards/11/members
Authorization: {{userToken}}
Content-Type: application/json