create table profiles (
  created_at timestamp(6) not null,
  id bigint generated by default as identity,
  updated_at timestamp(6),
  avatar varchar(255),
  name varchar(255) not null,
  primary key (id)
);

create table users (
  deleted_at boolean not null,
  created_at timestamp(6) not null,
  id bigint generated by default as identity,
  profile_id bigint unique,
  updated_at timestamp(6),
  email varchar(255) not null unique,
  password varchar(255) not null,
  primary key (id)
);

comment on column users.deleted_at is 'Soft-delete indicator';

alter table if exists users 
  add constraint FKq2e6rj0p6p1gec2cslmaxugw1 
  foreign key (profile_id) 
  references profiles;
