create table profiles (created_at timestamp(6) not null, id bigint generated by default as identity, updated_at timestamp(6), avatar varchar(255), name varchar(255) not null, primary key (id));
create table users (created_at timestamp(6) not null, deleted_at timestamp(6), id bigint generated by default as identity, profile_id bigint unique, updated_at timestamp(6), email varchar(255) not null unique, password varchar(255) not null, primary key (id));
alter table if exists users add constraint FKq2e6rj0p6p1gec2cslmaxugw1 foreign key (profile_id) references profiles;
