
CREATE TYPE public."PermissionType" AS ENUM ('SYSTEM', 'BOARD');

create table board_role_board_permission (
    board_role_id bigint not null,
    permission_id bigint not null,
    primary key (board_role_id, permission_id)
);

create table board_roles (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table permissions (
    id bigint generated by default as identity,
    name varchar(255) not null,
    type varchar(255) not null check ((type in ('SYSTEM','BOARD'))),
    primary key (id)
);

create table system_role_system_permission (
    system_role_id bigint not null,
    permission_id bigint not null,
    primary key (system_role_id, permission_id)
);

create table system_roles (
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

alter table if exists board_roles 
    drop constraint if exists UKb3x2mqvep70mn9xsepso0o8qy;

alter table if exists board_roles 
    add constraint UKb3x2mqvep70mn9xsepso0o8qy unique (name);

alter table if exists permissions 
    drop constraint if exists UKpnvtwliis6p05pn6i3ndjrqt2;

alter table if exists permissions 
    add constraint UKpnvtwliis6p05pn6i3ndjrqt2 unique (name);

alter table if exists system_roles 
    drop constraint if exists UK62dv2k9crwiu959lu1vy273xu;

alter table if exists system_roles 
    add constraint UK62dv2k9crwiu959lu1vy273xu unique (name);

alter table if exists board_role_board_permission 
    add constraint FK1qy7mgo9lrphf23w5r6jgr6dx 
    foreign key (permission_id) 
    references permissions;

alter table if exists board_role_board_permission 
    add constraint FKrpfhwpkm9j5rhkbkbjyv3hoar 
    foreign key (board_role_id) 
    references board_roles;

alter table if exists system_role_system_permission 
    add constraint FKsf4jbhdit25m8ylcsigjlfjgw 
    foreign key (permission_id) 
    references permissions;

alter table if exists system_role_system_permission 
    add constraint FK6chlpvsrh9lq6ju6p4re5xdl6 
    foreign key (system_role_id) 
    references system_roles;
