CREATE TYPE public."PermissionType" AS ENUM ('SYSTEM', 'BOARD');

create table board_role_board_permission (
    board_role_id bigint not null,
    permission_id bigint not null,
    primary key (board_role_id, permission_id)
);

create table board_roles (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table permissions (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    type varchar(255) not null check ((type in ('SYSTEM','BOARD'))),
    primary key (id)
);

create table profiles (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    avatar varchar(255),
    name varchar(255) not null,
    primary key (id)
);

create table system_role_system_permission (
    permission_id bigint not null,
    system_role_id bigint not null,
    primary key (permission_id, system_role_id)
);

create table system_roles (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table users (
    deleted_at boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    profile_id bigint unique,
    system_role_id bigint,
    updated_at timestamp(6),
    email varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

comment on column users.deleted_at is
    'Soft-delete indicator';

alter table if exists board_role_board_permission 
    add constraint FKaw9pp4sjvr1d7sewb7suyg06d 
    foreign key (permission_id) 
    references permissions;

alter table if exists board_role_board_permission 
    add constraint FKjr0eq6lyn8p1f2cmt7c568g8b 
    foreign key (board_role_id) 
    references board_roles;

alter table if exists system_role_system_permission 
    add constraint FKcva0p7vxobvruqq5r1dbl6tl5 
    foreign key (permission_id) 
    references permissions;

alter table if exists system_role_system_permission 
    add constraint FK8p8g5h94wy2c75f5u9tuawanr 
    foreign key (system_role_id) 
    references system_roles;

alter table if exists users 
    add constraint FKq2e6rj0p6p1gec2cslmaxugw1 
    foreign key (profile_id) 
    references profiles;

alter table if exists users 
    add constraint FKp8xf0esk14sv0yjgflluq0qoy 
    foreign key (system_role_id) 
    references system_roles;
